### ISSUE TITLE
ERROR: failed to solve: process "gem install fluent-plugin-grafana-loki" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by pjp-comp** [ishanvyas22/cakephp-loki-demo#76]
while docker build -t cakephp-loki-fluentd ./fluentd getting this error
ERROR: failed to solve: process "gem install fluent-plugin-grafana-loki" did not complete successfully: exit code: 1

**Comment by ishanvyas22** [comment]
Seems to be problem with the fluent-plugin-grafana-loki gem (https://github.com/grafana/loki/issues/719).
